-- AlterTable
ALTER TABLE "Campaign" DROP COLUMN "characters",
DROP COLUMN "description",
DROP COLUMN "difficulty",
DROP COLUMN "encounters",
DROP COLUMN "estimatedDuration",
DROP COLUMN "items",
DROP COLUMN "levelRange",
DROP COLUMN "locations",
DROP COLUMN "mainPlot",
DROP COLUMN "majorNPCs",
DROP COLUMN "notes",
DROP COLUMN "npcs",
DROP COLUMN "playerCount",
DROP COLUMN "portrait",
DROP COLUMN "quests",
DROP COLUMN "setting",
DROP COLUMN "subPlots",
DROP COLUMN "theme",
RENAME COLUMN "campaignJson" TO "data";

-- AlterTable
ALTER TABLE "Character" DROP COLUMN "alignment",
DROP COLUMN "armorClass",
DROP COLUMN "background",
DROP COLUMN "backstory",
DROP COLUMN "features",
DROP COLUMN "hitPoints",
DROP COLUMN "initiative",
DROP COLUMN "personalityTraits",
DROP COLUMN "portrait",
DROP COLUMN "proficiencies",
DROP COLUMN "quote",
DROP COLUMN "speed",
DROP COLUMN "stats",
DROP COLUMN "uniqueTrait",
RENAME COLUMN "characterJson" TO "data";

-- AlterTable
ALTER TABLE "Encounter" DROP COLUMN "difficulty",
DROP COLUMN "enemies",
DROP COLUMN "environment",
DROP COLUMN "estimatedDuration",
DROP COLUMN "hazards",
DROP COLUMN "levelRange",
DROP COLUMN "objectives",
DROP COLUMN "portrait",
DROP COLUMN "reinforcements",
DROP COLUMN "rewards",
DROP COLUMN "tactics",
DROP COLUMN "terrain",
RENAME COLUMN "encounterJson" TO "data";

-- AlterTable
ALTER TABLE "Item" DROP COLUMN "attunement",
DROP COLUMN "craftingMaterials",
DROP COLUMN "description",
DROP COLUMN "enchantments",
DROP COLUMN "history",
DROP COLUMN "magicalEffects",
DROP COLUMN "portrait",
DROP COLUMN "properties",
DROP COLUMN "quote",
DROP COLUMN "requirements",
DROP COLUMN "restrictions",
DROP COLUMN "uniqueTrait",
DROP COLUMN "value",
DROP COLUMN "weight",
RENAME COLUMN "itemJson" TO "data";

-- AlterTable
ALTER TABLE "NPC" DROP COLUMN "appearance",
DROP COLUMN "backstory",
DROP COLUMN "equipment",
DROP COLUMN "goals",
DROP COLUMN "location",
DROP COLUMN "mood",
DROP COLUMN "motivations",
DROP COLUMN "personality",
DROP COLUMN "personalityTraits",
DROP COLUMN "portrait",
DROP COLUMN "quote",
DROP COLUMN "relationships",
DROP COLUMN "secrets",
DROP COLUMN "skills",
DROP COLUMN "stats",
DROP COLUMN "uniqueTrait",
RENAME COLUMN "npcJson" TO "data";

-- AlterTable
ALTER TABLE "Quest" DROP COLUMN "consequences",
DROP COLUMN "description",
DROP COLUMN "difficulty",
DROP COLUMN "estimatedDuration",
DROP COLUMN "levelRange",
DROP COLUMN "location",
DROP COLUMN "npcs",
DROP COLUMN "objectives",
DROP COLUMN "portrait",
DROP COLUMN "questType",
DROP COLUMN "rewards",
DROP COLUMN "timeline",
RENAME COLUMN "questJson" TO "data";

-- AlterTable
ALTER TABLE "World" DROP COLUMN "climate",
DROP COLUMN "conflicts",
DROP COLUMN "culture",
DROP COLUMN "economy",
DROP COLUMN "geography",
DROP COLUMN "government",
DROP COLUMN "history",
DROP COLUMN "landmarks",
DROP COLUMN "legends",
DROP COLUMN "majorFactions",
DROP COLUMN "notableEvents",
DROP COLUMN "politics",
DROP COLUMN "population",
DROP COLUMN "portrait",
DROP COLUMN "quote",
DROP COLUMN "religion",
DROP COLUMN "resources",
DROP COLUMN "uniqueFeature",
RENAME COLUMN "worldJson" TO "data";
